### ISSUE TITLE
CV-90 30mm and MG gun performance

### ISSUE THREAD

**Issue by DJPatetin** [2bnb/2bnb-extras#169] opened 2020-09-09 20:22 UTC
Arma 3 vanilla autocannons are trash
MP-T rounds are coded so they can be used against armored vehicles so they bounce from the ground and have pitifull explosive damage (also present in vanilla tanks)

AP is ok

LMG doesn't work well since the tracer bullets and the non tracers have different ballistics(or its just a glitch with vanilla vics in general) so over 400meters away, the tracer rounds will land to the left of where you're aiming but the non tracer will hit where you have aimed. So you're pretty much going to miss half of your bullets by default. 

All of these are not present with RHS(or modded vics in general as long as it's not a vanilla clone) like the bradley wich has custom HEFI shells that allways explode on contact and kill in one or two hits within 2 meters

**Comment by Saborknight** [comment] 2020-09-12 03:06
Hopefully below commit helps out

**Comment by Saborknight** [comment] 2020-09-12 03:07
#168 is a duplicate of this

**Comment by Saborknight** [comment] 2020-09-13 10:12
The new performance of the CV90 armaments has now been rated 8/10 by our lord and saviour @DJPatetin . This is a satisfactory result, and therefore means the issue is now closed.

**Closed as completed by Saborknight** 2020-09-13 10:12 UTC
